# Generated by Django 4.1.4 on 2023-01-20 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='Course',
            new_name='Course_id',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Course',
            new_name='Course_id',
        ),
        migrations.AlterField(
            model_name='books',
            name='AuthorName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='books',
            name='BookName',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Issue_Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('End_date', models.DateField()),
                ('BookName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibraryApp.books')),
                ('Student_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibraryApp.student')),
            ],
        ),
    ]
